
@Composable
fun SetupScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(lang.setup_title) })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Text(lang.setup_loading)
            Button(onClick = { /* Handle Done */ }) {
                Text(lang.setup_done_button)
            }
        }
    }
}

@Composable
fun HomeScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text("Home") })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Top,
            horizontalAlignment = Alignment.Start
        ) {
            Text(lang.friend_clan_title)
            Text(lang.friend_player_title)
        }
    }
}

@Composable
fun UpdateScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(lang.update_version_title) })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Top,
            horizontalAlignment = Alignment.Start
        ) {
            Text(lang.update_app_version)
            Text(lang.update_game_version)
        }
    }
}

@Composable
fun WikiScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(lang.wiki_section_title) })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Top,
            horizontalAlignment = Alignment.Start
        ) {
            Text(lang.wiki_warships)
            Text(lang.wiki_upgrades)
            Text(lang.wiki_flags)
            Text(lang.wiki_skills)
        }
    }
}

@Composable
fun SettingsScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(lang.settings_app_settings) })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Top,
            horizontalAlignment = Alignment.Start
        ) {
            Text(lang.setting_game_server)
            Text(lang.setting_api_language)
            Text(lang.settings_app_dark_mode)
            Text(lang.settings_app_theme_colour)
        }
    }
}

@Composable
fun ErrorScreen() {
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(lang.error_title) })
        }
    ) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(16.dp),
            verticalArrangement = Arrangement.Center,
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Text(lang.error_download_issue)
        }
    }
}

@Preview(showBackground = true)
@Composable
fun PreviewSetupScreen() {
    SetupScreen()
}

    "setup_title" to "设置 WoWs Info",
    "setup_done_button" to "完成",
    "setup_loading" to "加载中...",
    "friend_clan_title" to "工会",
    "friend_player_title" to "玩家",
    "update_version_title" to "版本信息",
    "update_app_version" to "APP版本 ->",
    "update_game_version" to "游戏版本 ->",
    "button_settings_label" to "设置",
    "button_menu_label" to "主菜单",
    "button_back_label" to "返回",
    "button_home_label" to "主页面",
    "wiki_warship_footer" to "筛选",
    "wiki_warship_filter_btn" to "确定",
    "wiki_warship_reset_btn" to "还原",
    "wiki_warship_filter_placeholder" to "输入船名",
    "wiki_warship_filter_tier" to "等级",
    "wiki_warship_filter_nation" to "国家/区域",
    "wiki_warship_filter_type" to "类型",
    "wiki_warship_filter_premium" to "金币船",
    "warship_unknown" to "未知",
    "warship_model" to "3D模型",
    "warship_update_module" to "更新组件",
    "warship_default_module" to "默认组件",
    "warship_apply_module" to "确定",
    "warship_survivability" to "生存力",
    "warship_survivability_health" to "血量",
    "warship_survivability_armour" to "装甲",
    "warship_survivability_protection" to "防护",
    "warship_artillery" to "火炮",
    "warship_artillery_main" to "主炮",
    "warship_avg_damage" to "平均伤害",
    "warship_avg_winrate" to "平均胜率",
    "warship_avg_frag" to "平均击杀",
    "warship_weapon_reload" to "装填时间",
    "warship_weapon_range" to "射程",
    "warship_weapon_configuration" to "配置",
    "warship_weapon_dispersion" to "最大散布",
    "warship_weapon_rotation" to "转动时间",
    "warship_weapon_fire_chance" to "点火率",
    "warship_artillery_main_weight" to "重量",
    "warship_weapon_damage" to "最大伤害",
    "warship_weapon_potential_damage" to "潜在伤害",
    "warship_weapon_ap_overmatch" to "碾压",
    "warship_weapon_he_penetration" to "穿深",
    "warship_weapon_speed" to "速度",
    "warship_ramming" to "冲撞",
    "warship_artillery_secondary" to "副炮",
    "warship_torpedoes" to "鱼雷",
    "warship_torpedoes_visible_distance" to "探测距离",
    "warship_antiaircraft" to "防空",
    "warship_maneuverability" to "机动性",
    "warship_maneuverability_turning" to "转舵半径",
    "warship_maneuverability_speed" to "最大航速",
    "warship_maneuverability_rudder_time" to "转舵时间",
    "warship_aircraft" to "飞机",
    "warship_concealment" to "隐蔽",
    "warship_concealment_detect_by_ship" to "被船发现距离",
    "warship_concealment_detect_by_plane" to "被飞机发现距离",
    "warship_upgrades" to "升级品",
    "warship_next_ship" to "可升级为",
    "warship_compare_similar" to "对比类似的战舰",
    "server_name" to listOf("俄服", "欧服", "美服", "亚服"),
    "setting_game_server" to "游戏服务器",
    "setting_api_language" to "API语言",
    "setting_api_update_data" to "更新服务器数据",
    "setting_api_update_data_title" to "如果感觉数据没有更新，请使用这个功能",
    "setting_api_update_data_update" to "更新数据",
    "setting_api_update_data_cancel" to "取消",
    "setting_app_language" to "WoWs Info 语言",
    "settings_api_settings" to "API 接口设置",
    "settings_app_settings" to "软件设置",
    "settings_app_dark_mode" to "夜间模式",
    "settings_app_theme_colour" to "主题颜色",
    "settings_app_no_image_mode" to "无图模式",
    "settings_app_swap_buttons" to "交换下面的按钮",
    "settings_app_send_feedback" to "反馈",
    "settings_app_send_feedback_subtitle" to "给开发者发邮件",
    "settings_app_report_issues" to "报告错误",
    "settings_app_write_review" to "给软件打分",
    "settings_app_write_review_title" to "关于评分和反馈",
    "settings_app_write_review_message" to "如果 APP 有任何问题或者建议，请给开发者发送电子邮件，我们可以一起讨论解决问题。",
    "settings_app_write_review_yes" to "发送邮件",
    "settings_app_write_review_no" to "给软件打分",
    "settings_app_share" to "分享",
    "settings_app_share_subtitle" to "如果喜欢使用 WoWs Info，记得分享给小伙伴们！",
    "settings_app_check_for_update" to "检查更新",
    "settings_app_no_update" to "已经是最新版本",
    "settings_app_has_update" to "下载 {0} 版本",
    "settings_open_source" to "开源相关",
    "settings_open_source_github" to "Github",
    "settings_open_source_licence" to "三方许可",
    "settings_open_source_licence_subtitle" to "WoWs Info 使用了很多优秀的三方组件",
    "menu_footer" to "开始搜索",
    "menu_search_player" to "玩家",
    "menu_search_clan" to "工会",
    "pro_upgrade_button" to "升级到专业版",
    "pro_title" to "WoWs Info 专业版",
    "pro_rs" to "实时数据 Beta 测试版",
    "pro_rs_subtitle" to "获得每一场战斗的实时数据",
    "pro_more_stats" to "更多详细数据",
    "pro_more_stats_subtitle" to "在玩家界面显示更多更详细的数据",
    "pro_quick_access_main" to "快速查看主账号",
    "pro_quick_access_main_subtitle" to "一键查看主账号的数据",
    "pro_support_development" to "支持开发",
    "pro_support_development_subtitle" to "还有更多功能正在开发中",
    "pro_50_off_until_re" to "初次购买有5折优惠",
    "pro_per_year" to "年",
    "pro_restore_pro" to "恢复购买",
    "iap_thx_for_support" to "感谢您的支持！",
    "iap_no_purchase_history" to "您尚未购买专业版",
    "iap_pro_expired" to "WoWs Info 专业版已到期",
    "search_player_online" to "在线",
    "wiki_section_title" to "战舰百科",
    "wiki_achievement" to "成就",
    "wiki_warships" to "战舰",
    "wiki_upgrades" to "升级品",
    "wiki_flags" to "旗子与迷彩",
    "wiki_skills" to "舰长技能",
    "wiki_skills_tier" to "等级",
    "wiki_skills_reset" to "还原",
    "wiki_skills_point" to "点",
    "wiki_maps" to "地图",
    "wiki_collections" to "收藏",
    "extra_section_title" to "其他",
    "extra_support_wowsinfo" to "支持 WoWs Info",
    "extra_wowsinfo_re" to "WoWs Info 梦回2016",
    "extra_wowsinfo_re_subtitle" to "尝试在开发中的全新版本",
    "extra_rs_beta" to "实时数据 Beta 测试版",
    "extra_rs_beta_download" to "在电脑上下载 RS",
    "extra_support_wowsinfo_subtitle" to "捐助以及广告",
    "support_paypal" to "贝宝",
    "support_patreon" to "Patreon",
    "support_wechat" to "微信",
    "website_title" to "网站",
    "website_official_site" to "战舰世界官网",
    "website_premium" to "战舰商城",
    "website_global_wiki" to "战舰全球百科",
    "website_dev_blog" to "开发者的脸书",
    "website_sea_group" to "SEA Group",
    "website_daily_bounce" to "The Daily Bounce",
    "website_numbers" to "战舰数字",
    "website_today" to "今日战舰",
    "website_ranking" to "玩家排行榜",
    "website_models" to "战舰模型",
    "website_game_models" to "GameModels3D",
    "website_stats_news_title" to "数据与最新消息",
    "website_official_title" to "官方网站",
    "website_utility_title" to "实用工具",
    "website_ap_calculator" to "AP 曲线计算器",
    "website_wowsft" to "WoWs Fitting Tool",
    "website_ingame_title" to "游戏内网站",
    "website_wargaming_login" to "登陆 Wargming.net",
    "website_wargaming_login_subtitle" to "需要登陆才可以使用下面的网站，推荐使用大屏设备",
    "website_userbonus" to "我的奖赏",
    "website_news_ingame" to "游戏内新闻",
    "website_ingame_armory" to "我的武器库",
    "website_ingame_clan" to "我的工会",
    "website_ingame_warehouse" to "我的仓库",
    "website_my_logbook" to "我的航海日志",
    "content_creator_title" to "內容創作者",
    "content_creator_official" to "战舰世界官方频道",
    "content_creator_official_link" to "bilibili://space/573693898",
    "content_creator_fubuki" to "青空雪舞Channel",
    "content_creator_fubuki_link" to "bilibili://space/15653565",
    "tool_title" to "工具",
    "tab_achievement_title" to "成就",
    "tab_graph_title" to "图表",
    "tab_ship_title" to "战舰",
    "tab_rank_title" to "排位赛",
    "rating_title" to "个人评分",
    "rating_description" to "用来测量玩家的技能",
    "rating_read_more" to "- 阅读更多 -",
    "rating_warning" to "请不要只用数据来评价玩家",
    "rating_author" to "舰长 Wiochi",
    "rating_scale" to "评分表",
    "rating_bad" to "还需努力",
    "rating_below_average" to "低于平均",
    "rating_average" to "平均水平",
    "rating_good" to "好",
    "rating_very_good" to "很好",
    "rating_great" to "非常好",
    "rating_unicum" to "大佬平均",
    "rating_super_unicum" to "神佬平均",
    "rating_unknown" to "水平未知",
    "basic_data_unknown" to "未知",
    "basic_level_tier" to "等级",
    "basic_register_date" to "注册日期",
    "basic_last_battle" to "最后的战斗",
    "basic_more_stat" to "- 显示更多数据 -",
    "basic_add_friend" to "增加到列表",
    "basic_set_main" to "设为主账号",
    "detailed_win" to "胜利",
    "detailed_draw" to "平局",
    "detailed_loss" to "失败",
    "detailed_survived" to "存活场数",
    "detailed_total_xp" to "总经验",
    "detailed_survived_win" to "存活胜利",
    "detailed_survival_rate" to "生存率",
    "detailed_survived_win_rate" to "存活胜率",
    "detailed_total_potential_damage" to "总潜在伤害",
    "detailed_avg_potential_damage" to "平均潜在伤害",
    "detailed_total_torp_potential_damage" to "鱼雷潜在伤害",
    "detailed_avg_torp_potential_damage" to "平均鱼雷潜在伤害",
    "detailed_total_scouting_damage" to "总侦查伤害",
    "detailed_avg_scouting_damage" to "平均侦查伤害",
    "detailed_total_damage" to "总伤害",
    "detailed_damage_potential_ratio" to "真实伤害 / 潜在伤害",
    "detailed_total_spotted" to "总侦测数",
    "detailed_avg_spotted" to "平均侦测",
    "detailed_total_frag" to "总击杀",
    "detailed_frag_spot_ratio" to "击杀 / 侦测",
    "detailed_total_plane_killed" to "总飞机击落",
    "detailed_avg_plane_killed" to "平均飞机击落",
    "ship_detail_damage" to "伤害",
    "ship_detail_winrate" to "胜率",
    "ship_detail_frag" to "击杀",
    "ship_sort_battle" to "场数",
    "ship_sort_colour" to "颜色",
    "rank_season_title" to "赛季",
    "clan_created_date" to "创建于",
    "clan_creator_name" to "创建者",
    "clan_leader_name" to "指挥官",
    "clan_member_title" to "成员",
    "record_title" to "记录",
    "record_best_ship" to "最好",
    "record_max_damage_dealt" to "最大伤害",
    "record_max_frags_battle" to "最多击杀",
    "record_max_planes_killed" to "最多飞机击落",
    "record_max_xp" to "最多经验",
    "record_max_ships_spotted" to "最多侦测",
    "record_max_total_agro" to "最大潜在伤害",
    "record_max_damage_scouting" to "最大侦查伤害",
    "weapon_max_frags" to "最多击杀",
    "weapon_total_frags" to "总击杀",
    "weapon_hit_ratio" to "命中率",
    "app_name" to "WoWs Info 赛文",
    "wowsinfo_black" to "黑",
    "wowsinfo_white" to "白",
    "wowsinfo_ultra" to "超级版",
    "wowsinfo_ultimate" to "究极版",
    "wowsinfo_pro" to "专业版",
    "wowsinfo_new" to "新",
    "wowsinfo_go" to "GO",
    "wowsinfo_origin" to "起源",
    "wowsinfo_free" to "自由版",
    "rs_tip_download" to "1. 下载",
    "rs_tip_one" to "请访问此 Github 仓库并下载最新版本。此程序不使用大量的 RAM 和存储空间。目前，它处于测试阶段，没有 GUI。\n",
    "rs_tip_setup" to "2. 设置",
    "rs_tip_two" to "将您游戏文件夹的路径复制并粘贴到此程序中，您必须以管理员身份运行它，否则它将无法工作。它不会对您的计算机造成任何危害。\n",
    "rs_tip_enjoy" to "3. 使用RS",
    "rs_tip_three" to "输入您在屏幕上看到的 IP 地址，WoWs Info 将开始为您提供双方的实时统计数据。\n",
    "error_title" to "错误",
    "error_download_issue" to "无法更新数据，\n请稍后重试。\n\n如果问题依然存在，请尝试修改DNS为【8.8.8.8】或者使用VPN。\n如果还是不可以的话，说明服务器正在维护中。",
    "error_timeout" to "请求超时",
    "error_pr_corrupted" to "无法下载评分数据",
    "about_github_link" to "https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md"
)

    "setup_title" to "設定 WoWs Info",
    "setup_done_button" to "完成",
    "setup_loading" to "載入中...",
    "friend_clan_title" to "公會",
    "friend_player_title" to "玩家",
    "update_version_title" to "版本資訊",
    "update_app_version" to "APP版本 ->",
    "update_game_version" to "遊戲版本 ->",
    "button_settings_label" to "設定",
    "button_menu_label" to "主選單",
    "button_back_label" to "返回",
    "button_home_label" to "主頁面",
    "wiki_warship_footer" to "篩選",
    "wiki_warship_filter_btn" to "確定",
    "wiki_warship_reset_btn" to "還原",
    "wiki_warship_filter_placeholder" to "輸入艦名",
    "wiki_warship_filter_tier" to "階級",
    "wiki_warship_filter_nation" to "國家/地區",
    "wiki_warship_filter_type" to "類型",
    "wiki_warship_filter_premium" to "金幣艦",
    "warship_unknown" to "未知",
    "warship_model" to "3D模型",
    "warship_update_module" to "更新模組",
    "warship_default_module" to "預設模組",
    "warship_apply_module" to "確定",
    "warship_survivability" to "生存力",
    "warship_survivability_health" to "血量",
    "warship_survivability_armour" to "裝甲",
    "warship_survivability_protection" to "防護",
    "warship_artillery" to "火炮",
    "warship_artillery_main" to "主炮",
    "warship_avg_damage" to "平均傷害",
    "warship_avg_winrate" to "平均勝率",
    "warship_avg_frag" to "平均擊殺",
    "warship_weapon_reload" to "裝填時間",
    "warship_weapon_range" to "射程",
    "warship_weapon_configuration" to "配置",
    "warship_weapon_dispersion" to "最大散步",
    "warship_weapon_rotation" to "轉動時間",
    "warship_weapon_fire_chance" to "點火率",
    "warship_artillery_main_weight" to "重量",
    "warship_weapon_damage" to "最大傷害",
    "warship_weapon_potential_damage" to "潛在傷害",
    "warship_weapon_ap_overmatch" to "碾壓",
    "warship_weapon_he_penetration" to "穿深",
    "warship_weapon_speed" to "速度",
    "warship_ramming" to "衝撞",
    "warship_artillery_secondary" to "副炮",
    "warship_torpedoes" to "魚雷",
    "warship_torpedoes_visible_distance" to "探測距離",
    "warship_antiaircraft" to "防空",
    "warship_maneuverability" to "機動性",
    "warship_maneuverability_turning" to "轉舵半徑",
    "warship_maneuverability_speed" to "最大航速",
    "warship_maneuverability_rudder_time" to "轉舵時間",
    "warship_aircraft" to "飛機",
    "warship_concealment" to "隱蔽",
    "warship_concealment_detect_by_ship" to "被船發現距離",
    "warship_concealment_detect_by_plane" to "被飛機發現距離",
    "warship_upgrades" to "升級品",
    "warship_next_ship" to "可升級為",
    "warship_compare_similar" to "對比類似的戰艦",
    "server_name" to listOf("俄服", "歐服", "美服", "亞服"),
    "setting_game_server" to "遊戲伺服器",
    "setting_api_language" to "API語言",
    "setting_api_update_data" to "更新伺服器數據",
    "setting_api_update_data_title" to "如果感覺數據沒有更新，請使用這個功能",
    "setting_api_update_data_update" to "更新數據",
    "setting_api_update_data_cancel" to "取消",
    "setting_app_language" to "WoWs Info 語言",
    "settings_api_settings" to "API 介面設置",
    "settings_app_settings" to "軟體設置",
    "settings_app_dark_mode" to "夜間模式",
    "settings_app_theme_colour" to "主題顏色",
    "settings_app_no_image_mode" to "無圖模式",
    "settings_app_swap_buttons" to "交換下面的按鈕",
    "settings_app_send_feedback" to "反饋",
    "settings_app_send_feedback_subtitle" to "給開發者發郵件",
    "settings_app_report_issues" to "報告錯誤",
    "settings_app_write_review" to "給軟體打分",
    "settings_app_write_review_title" to "關於評分和反饋",
    "settings_app_write_review_message" to "如果有任何問題或者建議，請給開發者發送電子郵件，我們可以一起討論解決問題。",
    "settings_app_write_review_yes" to "發送郵件",
    "settings_app_write_review_no" to "給軟體打分",
    "settings_app_share" to "分享",
    "settings_app_share_subtitle" to "如果喜歡使用 WoWs Info，記得分享給小夥伴們！",
    "settings_app_check_for_update" to "檢查更新",
    "settings_app_no_update" to "已經是最新版本",
    "settings_app_has_update" to "下載 {0} 版本",
    "settings_open_source" to "開源相關",
    "settings_open_source_github" to "Github",
    "settings_open_source_licence" to "三方許可",
    "settings_open_source_licence_subtitle" to "WoWs Info 使用了很多優秀的三方組件",
    "menu_footer" to "開始搜索",
    "menu_search_player" to "玩家",
    "menu_search_clan" to "工會",
    "pro_upgrade_button" to "升級到專業版",
    "pro_title" to "WoWs Info 專業版",
    "pro_rs" to "實時數據 Beta 測試版",
    "pro_rs_subtitle" to "獲得每一場戰鬥的實時數據",
    "pro_more_stats" to "更多詳細數據",
    "pro_more_stats_subtitle" to "在玩家界面顯示更多更詳細的數據",
    "pro_quick_access_main" to "快速查看主帳號",
    "pro_quick_access_main_subtitle" to "一鍵查看主帳號的數據",
    "pro_support_development" to "支持開發",
    "pro_support_development_subtitle" to "還有更多功能正在開發中",
    "pro_50_off_until_re" to "初次購買有5折優惠",
    "pro_per_year" to "年",
    "pro_restore_pro" to "恢復購買",
    "iap_thx_for_support" to "感謝您的支持！",
    "iap_no_purchase_history" to "您尚未購買專業版",
    "iap_pro_expired" to "WoWs Info 專業版已到期",
    "search_player_online" to "在線",
    "wiki_section_title" to "戰艦百科",
    "wiki_achievement" to "成就",
    "wiki_warships" to "戰艦",
    "wiki_upgrades" to "升級品",
    "wiki_flags" to "旗子與迷彩",
    "wiki_skills" to "艦長技能",
    "wiki_skills_tier" to "等級",
    "wiki_skills_reset" to "還原",
    "wiki_skills_point" to "點",
    "wiki_maps" to "地圖",
    "wiki_collections" to "收藏",
    "extra_section_title" to "其他",
    "extra_support_wowsinfo" to "支持 WoWs Info",
    "extra_wowsinfo_re" to "WoWs Info 夢回2016",
    "extra_wowsinfo_re_subtitle" to "嘗試在開發中的全新版本",
    "extra_rs_beta" to "實時數據 Beta 測試版",
    "extra_rs_beta_download" to "在電腦上下載 RS",
    "extra_support_wowsinfo_subtitle" to "捐助以及廣告",
    "support_paypal" to "貝寶",
    "support_patreon" to "Patreon",
    "support_wechat" to "微信",
    "website_title" to "網站",
    "website_official_site" to "戰艦世界官網",
    "website_premium" to "戰艦商城",
    "website_global_wiki" to "戰艦全球百科",
    "website_dev_blog" to "開發者的臉書",
    "website_sea_group" to "SEA Group",
    "website_daily_bounce" to "The Daily Bounce",
    "website_numbers" to "戰艦數字",
    "website_today" to "今日戰艦",
    "website_ranking" to "玩家排行榜",
    "website_models" to "戰艦模型",
    "website_game_models" to "GameModels3D",
    "website_stats_news_title" to "數據與最新消息",
    "website_official_title" to "官方網站",
    "website_utility_title" to "實用工具",
    "website_ap_calculator" to "AP 曲線計算器",
    "website_wowsft" to "WoWs Fitting Tool",
    "website_ingame_title" to "遊戲內網站",
    "website_wargaming_login" to "登陸 Wargming.net",
    "website_wargaming_login_subtitle" to "需要登陸才可以使用下面的網站，推薦使用大屏設備",
    "website_userbonus" to "我的獎賞",
    "website_news_ingame" to "遊戲內新聞",
    "website_ingame_armory" to "我的武器庫",
    "website_ingame_clan" to "我的工會",
    "website_ingame_warehouse" to "我的倉庫",
    "website_my_logbook" to "我的航海日誌",
    "content_creator_title" to "社區貢獻者",
    "content_creator_official" to "戰艦世界官方頻道",
    "content_creator_official_link" to "bilibili://space/573693898",
    "content_creator_fubuki" to "青空雪舞Channel",
    "content_creator_fubuki_link" to "bilibili://space/15653565",
    "tool_title" to "工具",
    "tab_achievement_title" to "成就",
    "tab_graph_title" to "圖表",
    "tab_ship_title" to "戰艦",
    "tab_rank_title" to "排位賽",
    "rating_title" to "個人評分",
    "rating_description" to "用來測量玩家的技能",
    "rating_read_more" to "- 閱讀更多 -",
    "rating_warning" to "請不要只用數據來評價玩家",
    "rating_author" to "艦長 Wiochi",
    "rating_scale" to "評分表",
    "rating_bad" to "還需努力",
    "rating_below_average" to "低於平均",
    "rating_average" to "平均水平",
    "rating_good" to "好",
    "rating_very_good" to "很好",
    "rating_great" to "非常好",
    "rating_unicum" to "大佬平均",
    "rating_super_unicum" to "神佬平均",
    "rating_unknown" to "水平未知",
    "basic_data_unknown" to "未知",
    "basic_level_tier" to "等級",
    "basic_register_date" to "註冊日期",
    "basic_last_battle" to "最後的戰鬥",
    "basic_more_stat" to "- 顯示更多數據 -",
    "basic_add_friend" to "加為好友",
    "basic_set_main" to "設為主帳號",
    "detailed_win" to "勝利",
    "detailed_draw" to "平局",
    "detailed_loss" to "敗北",
    "detailed_survived" to "存活場數",
    "detailed_total_xp" to "總經驗",
    "detailed_survived_win" to "存活勝利",
    "detailed_survival_rate" to "生存率",
    "detailed_survived_win_rate" to "存活勝率",
    "detailed_total_potential_damage" to "總潛在傷害",
    "detailed_avg_potential_damage" to "平均潛在傷害",
    "detailed_total_torp_potential_damage" to "魚雷潛在傷害",
    "detailed_avg_torp_potential_damage" to "平均魚雷潛在傷害",
    "detailed_total_scouting_damage" to "總偵查傷害",
    "detailed_avg_scouting_damage" to "平均偵查傷害",
    "detailed_total_damage" to "總傷害",
    "detailed_damage_potential_ratio" to "實際傷害 / 潛在傷害",
    "detailed_total_spotted" to "總偵測數",
    "detailed_avg_spotted" to "平均偵測",
    "detailed_total_frag" to "總擊殺",
    "detailed_frag_spot_ratio" to "擊殺 / 偵測",
    "detailed_total_plane_killed" to "總擊落飛機數",
    "detailed_avg_plane_killed" to "平均擊落飛機數",
    "ship_detail_damage" to "傷害",
    "ship_detail_winrate" to "勝率",
    "ship_detail_frag" to "擊殺",
    "ship_sort_battle" to "場數",
    "ship_sort_colour" to "顏色",
    "rank_season_title" to "賽季",
    "clan_created_date" to "創建日期",
    "clan_creator_name" to "創建者",
    "clan_leader_name" to "指揮官",
    "clan_member_title" to "成員",
    "record_title" to "紀錄",
    "record_best_ship" to "最佳",
    "record_max_damage_dealt" to "最大傷害",
    "record_max_frags_battle" to "最多擊殺",
    "record_max_planes_killed" to "最多飛機擊落",
    "record_max_xp" to "最多經驗",
    "record_max_ships_spotted" to "最多偵測",
    "record_max_total_agro" to "最大潛在傷害",
    "record_max_damage_scouting" to "最大偵查傷害",
    "weapon_max_frags" to "最多擊殺",
    "weapon_total_frags" to "總擊殺",
    "weapon_hit_ratio" to "命中率",
    "app_name" to "WoWs Info 七號",
    "wowsinfo_black" to "黑",
    "wowsinfo_white" to "白",
    "wowsinfo_ultra" to "超級版",
    "wowsinfo_ultimate" to "究極版",
    "wowsinfo_pro" to "專業版",
    "wowsinfo_new" to "新",
    "wowsinfo_go" to "GO",
    "wowsinfo_origin" to "起源",
    "wowsinfo_free" to "自由版",
    "rs_tip_download" to "1. 下載",
    "rs_tip_one" to "請訪問此 Github 倉庫並下載最新版本。此程式不佔用大量 RAM 和儲存空間。目前處於測試階段並無 GUI 介面。\n",
    "rs_tip_setup" to "2. 設定",
    "rs_tip_two" to "將您的遊戲文件夾路徑複製並貼上至此程式中，然後以管理員身份運行程式，否則將無法運作。此程式不會對您的電腦造成任何損害。\n",
    "rs_tip_enjoy" to "3. 使用 RS",
    "rs_tip_three" to "輸入您在屏幕上看到的 IP 地址，WoWs Info 將開始為您的兩支隊伍提供即時統計數據。\n",
    "error_title" to "錯誤",
    "error_download_issue" to "無法更新數據，\n請稍後重試。\n\n如果問題仍然存在，請嘗試修改 DNS 為【8.8.8.8】或者使用 VPN。\n如果仍然無法解決，可能是服務器正在維護中。",
    "error_timeout" to "請求超時",
    "error_pr_corrupted" to "無法下載評分數據",
    "about_github_link" to "https://github.com/HenryQuan/WoWs-Info-Origin/blob/master/README.md"
)

    "setup_title" to "WoWs Infoの初期設定",
    "setup_done_button" to "完了",
    "setup_loading" to "読み込み中...",
    "friend_clan_title" to "クラン",
    "friend_player_title" to "プレーヤー",
    "update_version_title" to "バージョン",
    "update_app_version" to "アプリ ->",
    "update_game_version" to "ゲーム ->",
    "button_settings_label" to "設定",
    "button_menu_label" to "メニュー",
    "button_back_label" to "戻る",
    "button_home_label" to "ホーム",
    "wiki_warship_footer" to "フィルター",
    "wiki_warship_filter_btn" to "適用",
    "wiki_warship_reset_btn" to "リセット",
    "wiki_warship_filter_placeholder" to "名前を入力",
    "wiki_warship_filter_tier" to "ティア",
    "wiki_warship_filter_nation" to "国／地区",
    "wiki_warship_filter_type" to "艦種",
    "wiki_warship_filter_premium" to "プレミアム艦",
    "warship_unknown" to "不明",
    "warship_model" to "3Dモデル",
    "warship_update_module" to "モジュール変更",
    "warship_default_module" to "初期モジュール",
    "warship_apply_module" to "適用",
    "warship_survivability" to "生存力",
    "warship_survivability_health" to "HP",
    "warship_survivability_armour" to "装甲",
    "warship_survivability_protection" to "対水雷防御",
    "warship_artillery" to "火砲",
    "warship_artillery_main" to "主砲",
    "warship_avg_damage" to "平均ダメージ",
    "warship_avg_winrate" to "勝率",
    "warship_avg_frag" to "艦船撃沈",
    "warship_weapon_reload" to "装填時間",
    "warship_weapon_range" to "射程",
    "warship_weapon_configuration" to "配置",
    "warship_weapon_dispersion" to "最大散布",
    "warship_weapon_rotation" to "旋回時間",
    "warship_weapon_fire_chance" to "火災発生率",
    "warship_artillery_main_weight" to "重量",
    "warship_weapon_damage" to "最大ダメージ",
    "warship_weapon_potential_damage" to "潜在ダメージ",
    "warship_weapon_ap_overmatch" to "オーバーマッチ",
    "warship_weapon_he_penetration" to "装甲貫通力",
    "warship_weapon_speed" to "速度",
    "warship_ramming" to "体当たり",
    "warship_artillery_secondary" to "副砲",
    "warship_torpedoes" to "魚雷",
    "warship_torpedoes_visible_distance" to "探知距離",
    "warship_antiaircraft" to "対空火力",
    "warship_maneuverability" to "機動性",
    "warship_maneuverability_turning" to "旋回半径",
    "warship_maneuverability_speed" to "最大速度",
    "warship_maneuverability_rudder_time" to "転舵時間",
    "warship_aircraft" to "航空機",
    "warship_concealment" to "隠蔽性",
    "warship_concealment_detect_by_ship" to "海上探知距離",
    "warship_concealment_detect_by_plane" to "航空探知距離",
    "warship_upgrades" to "アップグレード",
    "warship_next_ship" to "次の艦",
    "warship_compare_similar" to "類似艦の比較",
    "server_name" to listOf("ロシア", "ヨーロッパ", "北アメリカ", "アジア"),
    "setting_game_server" to "ゲームサーバー",
    "setting_api_language" to "API言語",
    "setting_api_update_data" to "データ更新",
    "setting_api_update_data_title" to "データがない場合に使用",
    "setting_api_update_data_update" to "更新",
    "setting_api_update_data_cancel" to "キャンセル",
    "setting_app_language" to "WoWs Info言語",
    "settings_api_settings" to "API設定",
    "settings_app_settings" to "アプリ設定",
    "settings_app_dark_mode" to "ダークモード",
    "settings_app_theme_colour" to "テーマ色",
    "settings_app_no_image_mode" to "省データモード",
    "settings_app_swap_buttons" to "ボタン入れ替え",
    "settings_app_send_feedback" to "フィードバック",
    "settings_app_send_feedback_subtitle" to "開発者にメール",
    "settings_app_report_issues" to "問題報告",
    "settings_app_write_review" to "レビューを書く",
    "settings_app_write_review_title" to "レビューとフィードバック",
    "settings_app_write_review_message" to "アプリに関する質問、問題、提案は開発者にご連絡ください。",
    "settings_app_write_review_yes" to "開発者にメール",
    "settings_app_write_review_no" to "レビューを書く",
    "settings_app_share" to "シェア",
    "settings_app_share_subtitle" to "友達にシェア",
    "settings_app_check_for_update" to "アップデートを確認",
    "settings_app_no_update" to "最新バージョンです",
    "settings_app_has_update" to "アップデートあり {0}",
    "settings_open_source" to "オープンソース",
    "settings_open_source_github" to "Github",
    "settings_open_source_licence" to "ライセンス",
    "settings_open_source_licence_subtitle" to "本アプリに使用したモジュール",
    "menu_footer" to "検索",
    "menu_search_player" to "プレーヤー",
    "menu_search_clan" to "クラン",
    "pro_upgrade_button" to "プロバージョンにアップグレード",
    "pro_title" to "WoWs Info プロ",
    "pro_rs" to "リアルタイム統計 Beta",
    "pro_rs_subtitle" to "リアルタイムで戦闘情報を表示",
    "pro_more_stats" to "詳細情報",
    "pro_more_stats_subtitle" to "プレーヤー情報の詳細表示",
    "pro_quick_access_main" to "メインプレーヤー",
    "pro_quick_access_main_subtitle" to "ホームページでアカウントにアクセス",
    "pro_support_development" to "開発支援",
    "pro_support_development_subtitle" to "新機能の開発サポート",
    "pro_50_off_until_re" to "初回購入 50% OFF！",
    "pro_per_year" to "年間",
    "pro_restore_pro" to "購入済みの場合、ここをタップ",
    "iap_thx_for_support" to "ご支援ありがとうございます！",
    "iap_no_purchase_history" to "支払い履歴がありません",
    "iap_pro_expired" to "プロバージョンの有効期限が切れました",
    "search_player_online" to "オンライン",
    "wiki_section_title" to "百科事典",
    "wiki_achievement" to "実績",
    "wiki_warships" to "艦艇",
    "wiki_upgrades" to "アップグレード",
    "wiki_flags" to "信号旗",
    "wiki_skills" to "艦長スキル",
    "wiki_skills_tier" to "ティア",
    "wiki_skills_reset" to "リセット",
    "wiki_skills_point" to "ポイント",
    "wiki_maps" to "地図",
    "wiki_collections" to "コレクション",
    "extra_section_title" to "その他",
    "extra_support_wowsinfo" to "WoWs Info支援",
    "extra_wowsinfo_re_subtitle" to "開発中の新バージョン",
    "extra_wowsinfo_re" to "WoWs Info 2016年の夢",
    "extra_rs_beta" to "リアルタイム統計 Beta",
    "extra_rs_beta_download" to "パソコンでダウンロード",
    "extra_support_wowsinfo_subtitle" to "寄付と広告",
    "support_paypal" to "ペイパル",
    "support_patreon" to "パトレオン",
    "support_wechat" to "WeChat",
    "website_title" to "ウェブサイト",
    "website_official_site" to "World of Warships",
    "website_premium" to "プレミアムショップ",
    "website_global_wiki" to "グローバルウィキ",
    "website_dev_blog" to "開発者ブログ",
    "website_sea_group" to "シーグループ",
    "website_daily_bounce" to "デイリーバウンス",
    "website_numbers" to "WoWS Stats & Numbers",
    "website_today" to "Warships.Today",
    "website_ranking" to "プレーヤーランキング",
    "website_models" to "艦艇モデル",
    "website_game_models" to "GameModels3D",
    "website_stats_news_title" to "統計と情報",
    "website_official_title" to "公式サイト",
    "website_utility_title" to "ツール",
    "website_ap_calculator" to "APダメージ計算機",
    "website_wowsft" to "WoWs Fitting Tool",
    "website_ingame_title" to "ゲーム内サイト",
    "website_wargaming_login" to "Wargaming.net ログイン",
    "website_wargaming_login_subtitle" to "ログインして使う",
    "website_userbonus" to "私のボーナス",
    "website_news_ingame" to "ゲーム内ニュース",
    "website_ingame_armory" to "私の武器庫",
    "website_ingame_clan" to "私のクラン",
    "website_ingame_warehouse" to "私の倉庫",
    "website_my_logbook" to "私の航海記録",
    "content_creator_title" to "コンテンツクリエイター",
    "content_creator_official" to "WoWs公式チャンネル",
    "content_creator_official_link" to "https://www.youtube.com/user/worldofwarshipscom",
    "content_creator_fubuki" to "青空雪舞Channel",
    "content_creator_fubuki_link" to "bilibili://space/15653565",
    "tool_title" to "ツール",
    "tab_achievement_title" to "実績",
    "tab_graph_title" to "グラフ",
    "tab_ship_title" to "艦",
    "tab_rank_title" to "ランク",
    "rating_title" to "操艦評価",
    "rating_description" to "プレイヤーレベルの評価方法",
    "rating_read_more" to "- 詳細情報 -",
    "rating_warning" to "評価で人を判断しないでください",
    "rating_author" to "Wiochi艦長による",
    "rating_scale" to "評価スケール",
    "rating_bad" to "改善の余地あり",
    "rating_below_average" to "平均以下",
    "rating_average" to "平均",
    "rating_good" to "良好",
    "rating_very_good" to "とても良好",
    "rating_great" to "素晴らしい",
    "rating_unicum" to "ユニカム",
    "rating_super_unicum" to "スーパーユニカム",
    "rating_unknown" to "不明",
    "basic_data_unknown" to "不明",
    "basic_level_tier" to "レベル",
    "basic_register_date" to "登録日",
    "basic_last_battle" to "最後の戦闘",
    "basic_more_stat" to "- 詳細情報 -",
    "basic_add_friend" to "フレンド追加",
    "basic_set_main" to "メインプレーヤーに設定",
    "detailed_win" to "勝利",
    "detailed_draw" to "引き分け",
    "detailed_loss" to "敗北",
    "detailed_survived" to "生存",
    "detailed_total_xp" to "総XP",
    "detailed_survived_win" to "生存勝利",
    "detailed_survival_rate" to "生存率",
    "detailed_survived_win_rate" to "生存勝率",
    "detailed_total_potential_damage" to "総潜在ダメージ",
    "detailed_avg_potential_damage" to "平均潜在ダメージ",
    "detailed_total_torp_potential_damage" to "総水雷潜在ダメージ",
    "detailed_avg_torp_potential_damage" to "平均水雷潜在ダメージ",
    "detailed_total_scouting_damage" to "総探知ダメージ",
    "detailed_avg_scouting_damage" to "平均探知ダメージ",
    "detailed_total_damage" to "総与ダメージ",
    "detailed_damage_potential_ratio" to "与ダメージ / 潜在ダメージ",
    "detailed_total_spotted" to "総探知数",
    "detailed_avg_spotted" to "平均探知数",
    "detailed_total_frag" to "総撃沈数",
    "detailed_frag_spot_ratio" to "撃沈数 / 探知数",
    "detailed_total_plane_killed" to "総撃墜数",
    "detailed_avg_plane_killed" to "平均撃墜数",
    "ship_detail_damage" to "与ダメージ",
    "ship_detail_winrate" to "勝率",
    "ship_detail_frag" to "撃沈数",
    "ship_sort_battle" to "戦闘数",
    "ship_sort_colour" to "カラー",
    "rank_season_title" to "シーズン",
    "clan_created_date" to "設立日",
    "clan_creator_name" to "設立者",
    "clan_leader_name" to "クランマスター",
    "clan_member_title" to "メンバー",
    "record_title" to "最高記録",
    "record_best_ship" to "最良の艦",
    "record_max_damage_dealt" to "最大与ダメージ",
    "record_max_frags_battle" to "最大撃沈数",
    "record_max_planes_killed" to "最大撃墜数",
    "record_max_xp" to "最大XP",
    "record_max_ships_spotted" to "最大探知数",
    "record_max_total_agro" to "最大潜在ダメージ",
    "record_max_damage_scouting" to "最大探知ダメージ",
    "weapon_max_frags" to "最大撃沈数",
    "weapon_total_frags" to "総撃沈数",
    "weapon_hit_ratio" to "命中率",
    "app_name" to "WoWs Info セブン",
    "wowsinfo_black" to "黒",
    "wowsinfo_white" to "白",
    "wowsinfo_ultra" to "ウルトラ",
    "wowsinfo_ultimate" to "アルティメット",
    "wowsinfo_pro" to "プロ",
    "wowsinfo_new" to "ニュー",
    "wowsinfo_go" to "ゴー",
    "wowsinfo_origin" to "オリジン",
    "wowsinfo_free" to "フリー",
    "rs_tip_download" to "1. ダウンロード",
    "rs_tip_one" to "このGitHubリポジトリを訪問し、最新リリースをダウンロードしてください。 このプログラムは多くのRAMとストレージを使用しません。 現在、ベータステージにあり、GUIはありません。\n",
    "rs_tip_setup" to "2. セットアップ",
    "rs_tip_two" to "ゲームフォルダーのパスをこのプログラムにコピーして貼り付け、管理者として実行する必要があります。 そうしないと動作しません。 あなたのコンピューターに有害なことはありません。\n",
    "rs_tip_enjoy" to "3. 楽しむ",
    "rs_tip_three" to "画面に表示されるIPアドレスを入力すると、WoWs Infoが両チームのリアルタイムの統計情報を提供し始めます。\n",
    "error_title" to "エラー",
    "error_download_issue" to "アップデートのダウンロードに失敗しました。\n再試行してください。\n\n繰り返し失敗する場合は、VPNを使用したり、DNSを「8.8.8.8」に変更したりしてみてください。 メンテナンス中の可能性もあります。",
    "error_timeout" to "タイムアウト",
    "error_pr_corrupted" to "プレイヤーレートのデータがダウンロードできません"
)


@Composable
fun MyComponent() {
    var state by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Button(onClick = { state = !state }) {
            Text(text = if (state) "Active" else "Inactive")
        }
        Spacer(modifier = Modifier.height(16.dp))
        Text(text = "Current state: ${if (state) "Active" else "Inactive"}")
    }
}