@Serializable
data class Ability(
    val nation: String,
    val id: Int,
    val name: String,
    val icon: String,
    val description: String,
    val filter: String,
    val type: String,
    val abilities: Map<String, Modifiers>,
    val abilityList: List<Modifiers>,
    val alter: Map<String, AbilityAlter>?,
)

@Serializable
data class AbilityAlter(
    val name: String,
    val description: String,
)

@Serializable
data class AbilityInfo(
    val numConsumables: Int?,
    val preparationTime: Double?,
    val reloadTime: Double?,
    val workTime: Double?,
    val regenerationHPSpeed: Double?,
    val regenerationHPSpeedUnits: Double?,
    val areaDamageMultiplier: Double?,
    val bubbleDamageMultiplier: Double?,
    val climbAngle: Int?,
    val distanceToKill: Double?,
    val dogFightTime: Double?,
    val fightersName: String?,
    val fightersNum: Int?,
    val flyAwayTime: Double?,
    val radius: Double?,
    val timeDelayAttack: Double?,
    val timeFromHeaven: Double?,
    val timeToTryingCatch: Double?,
    val timeWaitDelayAttack: Double?,
    val artilleryDistCoeff: Double?,
    val activationDelay: Double?,
    val height: Double?,
    val lifeTime: Double?,
    val spawnBackwardShift: Double?,
    val speedLimit: Double?,
    val startDelayTime: Double?,
    val descIDs: String?,
    val iconIDs: String?,
    val titleIDs: String?,
    val backwardEngineForsag: Double?,
    val backwardEngineForsagMaxSpeed: Double?,
    val boostCoeff: Double?,
    val forwardEngineForsag: Double?,
    val forwardEngineForsagMaxSpeed: Double?,
    val distShip: Double?,
    val distTorpedo: Double?,
    val targetBuoyancyCoefficients: Map<String, Double>?,
    val torpedoReloadTime: Double?,
    val affectedClasses: List<String>?,
    val regenerationRate: Double?,
    val ammo: String?,
    val acousticWaveRadius: Double?,
    val updateFrequency: Double?,
    val zoneLifetime: Double?,
    val buoyancyRudderResetTimeCoeff: Double?,
    val buoyancyRudderTimeCoeff: Double?,
    val maxBuoyancySpeedCoeff: Double?,
    val underwaterMaxRudderAngleCoeff: Double?,
    val canUseOnEmpty: Boolean?,
    val logic: String?,
    val criticalChance: Double?,
    val source: List<String>?,
    val target: List<String>?,
    val zoneRadius: Double?,
    val allyAuraBuff: String?,
    val selfAuraBuff: String?,
    val startDistance: Double?,
    val waveDistance: Int?,
    val waveParams: String?,
    val absoluteBuff: String?,
    val condition: String?,
    val conditionalBuff: String?,
    val targetBuff: String?,
    val buoyancyState: Int?,
    val effectOnEndLongivity: Double?,
    val reloadBoostCoeff: Double?,
    val weaponTypes: List<String>?,
)